### ISSUE TITLE
Getting error: expected Post to respond to `has_searchable_field?`

### ISSUE THREAD

**Issue by vnatarajan-rpx** [pivotal/sunspot_matchers#32]
When I try to run rspec with the following line, I am getting this error.
`Post.should have_searchable_field(:title)`

```
Failure/Error: Post.should have_searchable_field(:title)
       expected Post to respond to `has_searchable_field?`
```

Can someone please help?

**Comment by jpalermo** [comment]
And you configured `config.include SunspotMatchers` in your spec helper?

https://github.com/pivotal/sunspot_matchers#installation-for-rspec

**Comment by vnatarajan-rpx** [comment]
Thanks. That worked.
When I tried to add that to `spec_helper.rb`, I got the following error:
`uninitialized constant SunspotMatchers (NameError)`

Now, I have moved that to `rails_helper.rb`. Now it is working fine.
